spring:
  datasource:
    url: jdbc:mysql://10.132.54.169:3305/lzy_database?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 741221
